name: QEC CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run unit tests
      run: |
        python test_correctness.py
    
    - name: Run smoke tests
      run: |
        cd experiments
        python quick_test.py --games 1 --live_details
        python run_simulation.py list_players
        cd ../research
        python run_qec_research.py list
    
    - name: Run performance tests
      run: |
        python profile_performance.py
    
    - name: Validate schema
      run: |
        python validate_schema.py logs || echo "Schema validation completed with warnings"
    
    - name: Test golden dataset
      run: |
        python create_golden_dataset.py
    
    - name: Generate test visualization
      run: |
        cd analysis
        python qec_visual_analyzer.py --input ../data/golden/golden_dataset.json --output ../test_plot.png
      continue-on-error: true
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.python-version }}
        path: |
          logs/
          data/golden/
          test_plot.png
        retention-days: 7

  build-docs:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx sphinx-rtd-theme
    
    - name: Build documentation
      run: |
        echo "Documentation build would go here"
        # sphinx-build -b html docs/ docs/_build/html
    
    - name: Upload documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/
        retention-days: 30
